services:
  frontend:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
