name: "Continuous Deployment Printscript-UI-Master"
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ElTaladro37
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/eltaladro37/printscript-ui-master:latest
          build-args: |
            VITE_AUTH_SERVER_URI=${{ secrets.VITE_AUTH_SERVER_URI }}
            VITE_AUTH_CLIENT_ID=${{ secrets.VITE_AUTH_CLIENT_ID }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
            "github_username=${{ github.actor }}"

      - name: Update service on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST_MAIN }}
          username: ${{ secrets.VM_USER_MAIN }}
          key: ${{ secrets.VM_KEY_MAIN }}
          script: |
            pwd
            cd TaladroInfra
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login -u ${{ github.actor }} --password-stdin ghcr.io
            sudo docker-compose pull printscript-ui
            sudo docker-compose up -d printscript-ui
